### ISSUE TITLE
Out of memory. size=262144

### ISSUE THREAD

**Issue by FezVrasta** [ianwalter/puppeteer#54]
Hi, I'm trying this action but I get an out of memory error for a lot of my test cases (they work fine on Travis).

```
[0411/173632.865431:FATAL:memory.cc(38)] Out of memory. size=262144
```

This is the log of the failed run:
https://github.com/popperjs/popper-core/runs/579393771?check_suite_focus=true

I read GitHub Actions have 7GB of RAM, but the error seems to mention a way smaller amount.

Ideas?

**Comment by ianwalter** [comment]
That is strange. Can you please try passing the chrome options `--disable-dev-shm-usage`
and / or `--disable-gpu`? If not, let me know and I can fork and try it at some later date.

**Comment by FezVrasta** [comment]
Sorry I migrated to `mujo-code/puppeteer-headful` and everything is working fine for me so I don't plan to spend more time on this issue.

**Comment by TotalLag** [comment]
i recently ran into this problem as well, not sure what changed when it had been working perfectly for a few months now.  this is the args i'm using:
```
args:[
        process.env.NODE_ENV == 'production' ? '--disable-gpu' : '--use-gl=desktop',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--no-first-run',
        '--window-size=768,950',
        '--headless',
        '--hide-scrollbars',
        '--mute-audio',
        "--proxy-server='direct://'",
        '--proxy-bypass-list=*',
        '--no-sandbox'
      ],
```
the page object crashes on navigation.

**Comment by ianwalter** [comment]
@TotalLag I think I've figured out the issue. This action uses an unstable version of chrome because of a historical issue between the stable version and puppeteer but it looks like that has been fixed. I'm going to move to the stable version and publish a new release in the next ~30 minutes.

@FezVrasta That action is based on this one, but you should probably use this one when I publish the next version unless you need Chrome to be headfull? Also, irrespective of which action you use, you should pin the action tag to the commit hash instead of specifying the branch name since the branch can be updated and cause your build to break or become insecure. I'll be updating this project's docs to reflect that soon.

**Comment by ianwalter** [comment]
@TotalLag If you can confirm this is fixed with `ianwalter/puppeteer@12728ddef82390d1ecd4732fb543f62177392fbb` AKA `ianwalter/puppeteer@3.0.0` I would appreciate it.

**Comment by TotalLag** [comment]
@ianwalter thank you for the quick turnaround!  Looks like everything is back in business again.  May want to change your README to refer `google-chrome-stable` now instead of `google-chrome-unstable` :)

**Comment by ianwalter** [comment]
Thanks!

**Comment by FezVrasta** [comment]
I'm still getting Out of memory with the recommended version

https://github.com/popperjs/popper-core/runs/699594741?check_suite_focus=true#step:6:21

**Comment by ianwalter** [comment]
@FezVrasta Don't have time right now, but I can clone, troubleshoot, and hopefully submit a PR tonight (EST).

**Comment by FezVrasta** [comment]
That'd be awesome! Thanks!
